### ISSUE TITLE
can't open azzamods.

### ISSUE THREAD

**Issue by saleh1111111111** [AzzaMediaGroup/AzzaModsLauncherReleases#2]
<img width="370" alt="Screenshot 2024-05-15 at 3 39 56 PM" src="https://github.com/AzzaMediaGroup/AzzaModsLauncherReleases/assets/169943449/39a30f92-7e11-47f2-bfcd-a372bcfe7e61">

**Comment by ash47** [comment]
The lack of these DLLs can be fixed by installing "Microsoft Visual C++ 2015 - 2022 Redistributable". AzzaMods depends on it being installed, normally it would automatically be installed, but something must have gone wrong.

Download from the links below. I suggest you install both the x86 and x64 versions. This is directly from Microsoft's website:
x86: https://aka.ms/vs/17/release/vc_redist.x86.exe
x64: https://aka.ms/vs/17/release/vc_redist.x64.exe
